#ifndef ERESULTADDMACADDRESS_H
#define ERESULTADDMACADDRESS_H

enum RESULTS_ADD_MAC_ADDRESS {
    CORRECT = 1,

    INCORRECT_LENGHT = -1,
    INCORRECT_MAC_ADDRESS_FORMAT = -2,
    INCORRECT_COLON_MAC_ADDRESS = -3,

    INCORRECT_INT_FORMAT = -5,
};

#endif